### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by sjauld** [gonzadocarmo/teamcity-s3-plugin#11]
Can you attach your zips to the release on Github instead of sticking them in Google Drive? It's difficult to download something from Google Drive using an automated tool like Packer...

**Comment by gonzadocarmo** [comment]
@sjauld check now, pls?

**Comment by sjauld** [comment]
Thanks so much! You're the best

**Comment by jufemaiz** [comment]
Def makes sense. 🎉🎉🎉
