### ISSUE TITLE
region: null

### ISSUE THREAD

**Issue by szemkhel** [gonzadocarmo/teamcity-s3-plugin#2]
I'm getting error while build:

>  The bucket is in this region: null.Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: XXXXXXXXXXXXXX) 

Plugin configured with region: _us-west-1_
Bucket based in: _US West (N. California)_

system:
```
TeamCity Professional 10.0.4 (build 42538)
Using CATALINA_BASE:   /usr/local/TeamCity
Using CATALINA_HOME:   /usr/local/TeamCity
Using CATALINA_TMPDIR: /usr/local/TeamCity/temp
Using JRE_HOME:        /
Using CLASSPATH:       /usr/local/TeamCity/bin/bootstrap.jar:/usr/local/TeamCity/bin/tomcat-juli.jar
Server version: Apache Tomcat/7.0.68
Server built:   Feb 8 2016 20:25:54 UTC
Server number:  7.0.68.0
OS Name:        Linux
OS Version:     3.10.0-327.10.1.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_121-b13
JVM Vendor:     Oracle Corporation
```

**Comment by gonzadocarmo** [comment]
While building the plugin? Are you able to get the "awsS3Plugin-agent.zip" under "build/target" folder?

**Comment by gonzadocarmo** [comment]
#7
