### ISSUE TITLE
Region field not used?

### ISSUE THREAD

**Issue by mbcrawfo** [gonzadocarmo/teamcity-s3-plugin#3]
The UI for this build step includes AWS region as a required field, but it looks like the value is never used, and the calls to S3 are defaulting to the us-west-1 region.  This is a problem for us because our TeamCity server is behind a firewall that only allows access to us-east-1, as it is the only region we use.  Any chance of having this field fully implemented?

**Comment by gonzadocarmo** [comment]
Logs pls?
In the meantime, can you try setting AWS_REGION env variable in teamcity "Parameters" section? Let me know if this helps...
