### ISSUE TITLE
Missing US-East-2 Region

### ISSUE THREAD

**Issue by newb23** [gonzadocarmo/teamcity-s3-plugin#8]
Labeled as Ohio in AWS' configuration setup.

**Comment by wjonker85** [comment]
First, I really like this plugin. To me it is more useful than the S3 artifacts plugin from JetBrains. 

I'am also missing some regions. The complete list can be found here : https://docs.aws.amazon.com/general/latest/gr/rande.html.

**Comment by gonzadocarmo** [comment]
Yeah, you're right. Thats coz the java sdk version is old. The regions are being taken dynamically from there. Will you be able to submit a PR upgrading that version? That should do it. thanks!

**Comment by gonzadocarmo** [comment]
@wjonker85 thanks! @newb23 , I've just updated and released a new version -0.1.2- Feel free to give it a try and reopen this if any issues. Thanks!
