### ISSUE TITLE
Region always reverted to US-west-2

### ISSUE THREAD

**Issue by wjonker85** [gonzadocarmo/teamcity-s3-plugin#9]
Reproduce:
- Save configuration with region eu-west-1
- Open configuration region is now set to us-west-2

**Comment by gonzadocarmo** [comment]
@wjonker85 , may I know what version of TC are u using? I've just tested it locally with 9.1.7 (build 37573) and I'm not seeing such issue.

**Comment by pierredeman** [comment]
We have same isue with : `TeamCity Enterprise 2019.1.3 (build 66439)`

**Comment by kinguru** [comment]
Same issue - latest TC 2020.1.3
